# Generated by Django 3.0.8 on 2020-08-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='staus',
            new_name='status',
        ),
    ]
